# Generated by Django 5.0.14 on 2026-02-25 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialusado',
            old_name='orden',
            new_name='orden_trabajo',
        ),
    ]
