# Generated by Django 5.0.14 on 2026-02-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_orden_materialusado_orden_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='ordenes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.ordentrabajo')),
            ],
        ),
    ]
