# Generated by Django 5.0.14 on 2026-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_imagenorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='anio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
