# Generated by Django 5.0.14 on 2026-02-25 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_vehiculo_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='anio',
            new_name='año',
        ),
    ]
