# Generated by Django 5.0.14 on 2026-02-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_anio_vehiculo_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiculo',
            old_name='año',
            new_name='anio',
        ),
    ]
