# Generated by Django 5.0.14 on 2026-02-26 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_año_vehiculo_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='material',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='material',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='materialusado',
            name='orden_trabajo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tecnico',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='tipo',
        ),
        migrations.AddField(
            model_name='materialusado',
            name='orden',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materiales_usados', to='core.ordentrabajo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='materialusado',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
