# Generated by Django 5.0.14 on 2026-02-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_cliente_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
