# Generated by Django 5.0.14 on 2026-02-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_ordentrabajo_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ordenes/'),
        ),
    ]
