# Generated by Django 5.0.14 on 2026-02-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ordentrabajo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='imagen',
        ),
    ]
